### ISSUE TITLE
hu_core_news_trf model spacy_transformers error? 

### ISSUE THREAD

**Issue by uveges** [huspacy/huspacy#63]
**Describe the bug**
When the model starts to analyze any given sentence, run stops with the following error code: 

```
Traceback (most recent call last):
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/examples/examples.py", line 11, in <module>
    main()
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/examples/examples.py", line 7, in main
    doc = nlp(test)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy/language.py", line 1047, in __call__
    error_handler(name, proc, [doc], e)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy/language.py", line 1042, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy_transformers/pipeline_component.py", line 192, in __call__
    outputs = self.predict([doc])
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy_transformers/pipeline_component.py", line 229, in predict
    activations = self.model.predict(docs)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/thinc/model.py", line 334, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy_transformers/layers/transformer_model.py", line 199, in forward
    model_output, bp_tensors = transformer(wordpieces, is_train)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/thinc/model.py", line 310, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/thinc/layers/pytorchwrapper.py", line 224, in forward
    Xtorch, get_dX = convert_inputs(model, X, is_train)
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/spacy_transformers/layers/transformer_model.py", line 227, in _convert_transformer_inputs
    "input_ids": xp2torch(wps.input_ids, device=hf_device),
  File "/home/istvanu/PycharmProjects/ABSA-PyTorch/venv/lib/python3.9/site-packages/thinc/util.py", line 401, in xp2torch
    torch_tensor = torch.utils.dlpack.from_dlpack(xp_tensor)
RuntimeError: from_dlpack received an invalid capsule. Note that DLTensor capsules can be consumed only once, so you might have already constructed a tensor from it once.
```

Used with: 
```
numpy>=1.13.3
torch==1.7.1
transformers==4.0.0
```
Also tested with torch==1.8.0, 1.8.1, 1.10.0, 1.10.1, 
and spacy==3.5.0, 3.6.1, 3.7.1, but resulted the same.

Model installed directly with the recommended pip command: 
`pip install https://huggingface.co/huspacy/hu_core_news_trf/resolve/main/hu_core_news_trf-any-py3-none-any.whl`

**To Reproduce**

Example code:
```
import hu_core_news_trf


def main():
    nlp = hu_core_news_trf.load()
    test = "Példa mondat."
    doc = nlp(test)


if __name__ == '__main__':
    main()
```

**Expected behavior**
A `doc` object should be created. `hu_core_news_lg` model works fine in the same venv.

**Additional context**

**Comment by oroszgy** [comment]
Hi there, thanks for the report! Could you please report your python version and the output of `pip freeze` as well?

Anyway, it looks to me that you might have a (Pytorch?) dependency issue. While I am trying to reproduce the bug, you might want to upgrade your dependencies and check whether is solves the problem.

**Comment by uveges** [comment]
transformer version seems to be the problem, therefore not related to huspacy! Thank you!
